"""Generate sparse_subsurface_export.ssrf from the anonymized fixture.

The anonymized fixture has every dive numbered and logging NDL and SAC. Real logs don't: the author's 197-dive log has 32 unnumbered dives, 24
unrated, 38 without tank pressure and 14 without SAC. This fixture has the
same kinds of gaps, one per dive, so the tests exercise them:

    #20       complete dive (control)
    unnumbered x2, inside a trip (trip name must survive)
    #22       no sac attribute and no pressure samples
    #23       no rating (the app ignores ratings; kept as a varied input)
    #24       no ndl samples
    #<deco>   a dive where the computer flagged in_deco='1'

Run from the repo root:  python tests/fixtures/make_sparse_fixture.py
"""

import copy
import xml.etree.ElementTree as ET  # trusted, checked-in input
from pathlib import Path

HERE = Path(__file__).parent
SOURCE = HERE / "anonymized_subsurface_export.ssrf"
TARGET = HERE / "sparse_subsurface_export.ssrf"


def main() -> None:
    root = ET.parse(SOURCE).getroot()
    dives_parent = root.find("dives")
    assert dives_parent is not None
    by_number = {d.get("number"): d for d in root.iter("dive")}
    deco_dive = next(
        d for d in root.iter("dive") if d.find(".//sample[@in_deco='1']") is not None
    )

    def clone(number: str) -> ET.Element:
        return copy.deepcopy(by_number[number])

    control = clone("20")
    unnumbered_a, unnumbered_b = clone("21"), clone("25")
    for dive in (unnumbered_a, unnumbered_b):
        del dive.attrib["number"]
    no_sac = clone("22")
    no_sac.attrib.pop("sac", None)
    for sample in no_sac.iter("sample"):
        sample.attrib.pop("pressure", None)
    for cyl in no_sac.iter("cylinder"):
        cyl.attrib.pop("start", None)
        cyl.attrib.pop("end", None)
    unrated = clone("23")
    unrated.attrib.pop("rating", None)
    no_ndl = clone("24")
    for sample in no_ndl.iter("sample"):
        sample.attrib.pop("ndl", None)
    deco = copy.deepcopy(deco_dive)

    trip = ET.Element(
        "trip", {"date": "2021-06-27", "time": "12:38:56", "location": "Sparse trip"}
    )
    trip.extend([control, unnumbered_a, unnumbered_b, no_sac, unrated, no_ndl])

    for child in list(dives_parent):
        dives_parent.remove(child)
    dives_parent.append(trip)
    dives_parent.append(deco)

    ET.indent(root)
    TARGET.write_text(
        "<!-- Generated by make_sparse_fixture.py; do not edit by hand. -->\n"
        + ET.tostring(root, encoding="unicode")
        + "\n"
    )
    print(f"Wrote {TARGET} (deco dive #{deco.get('number')})")


if __name__ == "__main__":
    main()
